repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [app/]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        name: mypy (app only)
        language: python
        always_run: true         # <—
        pass_filenames: false    # <—
        additional_dependencies:
          - mypy
        args:
          - -p
          - app
          - --ignore-missing-imports
          - --allow-untyped-globals
          - --allow-untyped-defs
          - --no-warn-return-any
