version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:latest
    container_name: stop_smoking_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db:5432/db
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app:cached
    depends_on:
      - db

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheduler:latest
    container_name: stop_smoking_scheduler
    command: python -m app.tasks.run_scheduler
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db:5432/db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app:cached
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
