"""badge condition time

Revision ID: 30a4bfc6a150
Revises: 781a4890eb84
Create Date: 2025-08-06 17:43:06.320003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a4bfc6a150'
down_revision: Union[str, None] = '781a4890eb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('condition_time', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'badges', ['condition_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'badges', type_='unique')
    op.drop_column('badges', 'condition_time')
    # ### end Alembic commands ###
