"""badge condition time not nullable

Revision ID: 43a6f551cd26
Revises: 30a4bfc6a150
Create Date: 2025-08-06 17:45:50.108569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a6f551cd26'
down_revision: Union[str, None] = '30a4bfc6a150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badges', 'condition_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badges', 'condition_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
