"""diaries

Revision ID: 4dd26a030f4a
Revises: 16e4386354d6
Create Date: 2025-08-03 20:33:36.936310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dd26a030f4a'
down_revision: Union[str, None] = '16e4386354d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cravings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('have_smoked', sa.Boolean(), nullable=False),
    sa.Column('desire_range', sa.Integer(), nullable=True),
    sa.Column('number_of_cigarets_smoked', sa.Integer(), nullable=True),
    sa.Column('feeling', sa.Text(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cravings_date'), 'cravings', ['date'], unique=False)
    op.create_index(op.f('ix_cravings_id'), 'cravings', ['id'], unique=False)
    op.create_table('diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('have_smoked', sa.Boolean(), nullable=False),
    sa.Column('craving_range', sa.Integer(), nullable=True),
    sa.Column('number_of_cravings', sa.Integer(), nullable=True),
    sa.Column('number_of_cigarets_smoked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diaries_date'), 'diaries', ['date'], unique=False)
    op.create_index(op.f('ix_diaries_id'), 'diaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diaries_id'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_date'), table_name='diaries')
    op.drop_table('diaries')
    op.drop_index(op.f('ix_cravings_id'), table_name='cravings')
    op.drop_index(op.f('ix_cravings_date'), table_name='cravings')
    op.drop_table('cravings')
    # ### end Alembic commands ###
