"""badge timestamps

Revision ID: 781a4890eb84
Revises: c9d3114d5ef7
Create Date: 2025-08-06 17:21:39.292151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781a4890eb84'
down_revision: Union[str, None] = 'c9d3114d5ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('badges', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'updated_at')
    op.drop_column('badges', 'created_at')
    # ### end Alembic commands ###
