"""pref cig data

Revision ID: 848d67949436
Revises: e03cd3e5454d
Create Date: 2025-08-03 01:41:53.196457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848d67949436'
down_revision: Union[str, None] = 'e03cd3e5454d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('cig_per_day', sa.Integer(), nullable=True))
    op.add_column('preferences', sa.Column('years_smoking', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'years_smoking')
    op.drop_column('preferences', 'cig_per_day')
    # ### end Alembic commands ###
