"""create daily_motivations table

Revision ID: 93a093210fc7
Revises: bc3244c44b54
Create Date: 2025-07-19 23:02:34.610690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a093210fc7'
down_revision: Union[str, None] = 'bc3244c44b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_motivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Text(), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('cravings', sa.Text(), nullable=False),
    sa.Column('ideas', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_motivations_date'), 'daily_motivations', ['date'], unique=False)
    op.create_index(op.f('ix_daily_motivations_id'), 'daily_motivations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_motivations_id'), table_name='daily_motivations')
    op.drop_index(op.f('ix_daily_motivations_date'), table_name='daily_motivations')
    op.drop_table('daily_motivations')
    # ### end Alembic commands ###
