"""pref cig price

Revision ID: 9970ebf5d6c7
Revises: 848d67949436
Create Date: 2025-08-03 16:53:29.511443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9970ebf5d6c7'
down_revision: Union[str, None] = '848d67949436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('cig_price', sa.Integer(), nullable=True, comment='Price per cigarette in local currency'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'cig_price')
    # ### end Alembic commands ###
