"""badges

Revision ID: a784d1e8d1c1
Revises: 4dd26a030f4a
Create Date: 2025-08-04 00:59:00.446697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a784d1e8d1c1'
down_revision: Union[str, None] = '4dd26a030f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_badges_user_id'), 'badges', ['user_id'], unique=False)
    op.create_foreign_key(None, 'badges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'badges', type_='foreignkey')
    op.drop_index(op.f('ix_badges_user_id'), table_name='badges')
    op.drop_column('badges', 'user_id')
    # ### end Alembic commands ###
