"""add language to preferences

Revision ID: ef23f1197fb7
Revises: 93a093210fc7
Create Date: 2025-07-22 22:12:07.166353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef23f1197fb7'
down_revision: Union[str, None] = '93a093210fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('language', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'language')
    # ### end Alembic commands ###
